# Generated by Django 5.2.12 on 2026-03-16 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('seen', 'Seen')], default='delivered', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='chatapp.message')),
            ],
            options={
                'unique_together': {('message', 'username')},
            },
        ),
    ]
