# Generated by Django 5.2.12 on 2026-03-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='gif_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagereceipt',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('seen', 'Seen')], max_length=20),
        ),
    ]
