# Generated by Django 5.2.12 on 2026-03-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_message_voice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='voice',
        ),
        migrations.AddField(
            model_name='message',
            name='voice_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
